Erick Rodriguez Martinez
+52 452-159-07-12
+1 653 325 81 15

# [PIP] Python Installation Packages

In [49]:
# xlrd is a library for reading data and formatting information from Excel files in the historical ".xls" format.
#@TODO Remove "#" to install "xlrd"
#!pip install xlrd
#!pip install openpyxl

# An open-source library that provides high-performance data manipulation in Python
#@TODO Remove "#" to install "pandas"
#!pip install pandas

# Python library dedicated to reading, manipulating and generating PDF documents
#@TODO Remove "#" to install "borb"
#!pip install borb

# [PLI] Python Library Imports

In [50]:
import pandas as pd
from pandas import ExcelWriter

import numpy as np

# [T-PLI] TEST Python Library Imports


In [ ]:
from decimal import Decimal

from borb.pdf import MultiColumnLayout
from borb.pdf import SingleColumnLayoutWithOverflow
from borb.pdf import PageLayout
from borb.pdf import TableUtil
from borb.pdf import TableCell

from borb.pdf import FlexibleColumnWidthTable
from borb.pdf import Paragraph
from borb.pdf import Document
from borb.pdf import Page
from borb.pdf import PDF
from borb.pdf.page.page_size import PageSize

# [FNC] Functions

In [1]:
def f_cleanTypeAndHierachy(dataFrame, typeCol, str1, hierachyCol, str2):
    """
    A class used to represent an Animal

    ...

    Attributes
    ----------
    says_str : str
        a formatted string to print out what the animal says
    name : str
        the name of the animal
    sound : str
        the sound that the animal makes
    num_legs : int
        the number of legs the animal has (default 4)

    Methods
    -------
    says(sound=None)
        Prints the animals name and what sound it makes
    """


    # Clean DataFrame Type Col -NaN- values and replace by str1
    _dataFrame = dataFrame
    _dataFrame.iloc[:, typeCol] = _dataFrame.iloc[:, typeCol].replace(np.nan, str1)

    # Clean DataFrame Hierarchy Col -Dots '.'- and replace by str2
    for i in range(len(_dataFrame.iloc[:, hierachyCol])):
        _dataFrame.iloc[i,hierachyCol] = str(_dataFrame.iat[i,hierachyCol]).replace('.', str2)

    return _dataFrame


def f_cleanBlankSpaces(dataFrame, col1):
    # Clean DataFrame values and replace by ''
    _dataFrame = dataFrame

    for i in range(len(_dataFrame.iloc[:, col1])):
        _dataFrame.iloc[i,col1] = str(_dataFrame.iat[i,col1]).replace(' ', '')

    return _dataFrame


def f_clearNaN(dataFrame, col1):
    _dataFrame = dataFrame

    for i in range(len(_dataFrame.iloc[:, col1])):
        _dataFrame.iloc[:, col1] = _dataFrame.iloc[:, col1].replace(np.nan, 'N/A')
    return  _dataFrame


def f_quantityUpdate(dataFrame, hierachyCol, quantityCol):
    _dataFrame = dataFrame

    row, column = _dataFrame.shape
    h = [0] * row
    c = [0] * row

    for i in range(len(_dataFrame.iloc[:,hierachyCol])):
        hierachy = len(str(_dataFrame.iat[i,hierachyCol]))
        quantityValue = _dataFrame.iat[i,quantityCol]
        sum = 0
        if hierachy == 1:
            h[1] = quantityValue
            c[i] = h[1]
        else:
            h[hierachy] = quantityValue
            c[i] = h[hierachy]
            for j in range(hierachy):
                if j == 0:
                    continue
                else:
                    c[i] = c[i] * h[j]
    #print(c) #@TODO Remove "#" to debug Quantity -[c]- Output

    for i in range(len(c)):
        _dataFrame.iloc[i,quantityCol] = c[i]

    return _dataFrame

def f_splitDataFrame(dataFrame, colN, str1):
    _dataFrame = dataFrame
    colSelect = _dataFrame[_dataFrame.columns[colN]]
    _dataFrame = _dataFrame[colSelect == str1]
    return  _dataFrame

def f_uniqueQuantity(dataFrame):
    _dataFrame = dataFrame
    row, col = _dataFrame.shape

    testValues = _dataFrame.iloc[:,1]
    testValues = testValues.unique()
    print(testValues)


    c = [0] * row
    found = [0] * len(testValues)
    quantity = [0] * len(testValues)
    iteration = 0
    rowToDelete = [0] * row
    uniqueDataFrame = _dataFrame

    for i in range(row):
        iteration = 0
        print(i)
        for j in testValues:
            if j == str(_dataFrame.iat[i,1]):
                if found[iteration] == 0:
                    found[iteration] = 1
                    quantity[iteration] += int(_dataFrame.iat[i,3])
                else:
                    quantity[iteration] += int(_dataFrame.iat[i,3])
                    rowToDelete[i] = _dataFrame.index.values[i]
                found[iteration] = 1
                print(found)
            iteration += 1

    for i in rowToDelete:
        if i != 0:
            uniqueDataFrame = uniqueDataFrame.drop(i)
            #print(j)

    print('Result')
    print(found)
    print(quantity)
    print(rowToDelete)

    iteration = 0
    for i in quantity:
        print(i)
        print(iteration)
        uniqueDataFrame.iat[iteration,3] = i
        iteration += 1
    return uniqueDataFrame


def f_rawMaterial(dataFrame, colSelect, sort1, sort2, colEvaluate):
    _dataFrame = dataFrame
    _dataFrame = _dataFrame[_dataFrame.columns[colSelect]]
    columnValues = _dataFrame.columns.values.tolist()
    #print(columnValues)

    _dataFrame = _dataFrame.sort_values(by=columnValues[sort1])
    _dataFrame = _dataFrame.sort_values(by=columnValues[sort2])

    _dataFrame = _dataFrame[_dataFrame[columnValues[colEvaluate]] > 0]
    return _dataFrame

# [T-FNC] TEST Functions

In [52]:
def f_uniqueRawQuantity(dataFrame):
    _dataFrame = dataFrame
    row, col = _dataFrame.shape

    testValues1 = _dataFrame.iloc[:, 1]
    testValues1 = testValues1.unique()
    print(testValues1)

    testValues2 = _dataFrame.iloc[:, 2]
    testValues2 = testValues2.unique()
    print(testValues2)

    c = [0] * row
    found = np.zeros((len(testValues1), len(testValues2)))

    quantity = np.zeros((len(testValues1), len(testValues2)))

    rowToDelete = [0] * row

    uniqueDataFrame = _dataFrame
    selectCols = _dataFrame.columns

    for i in range(row):
        i_iteration = 0
        j_iteration = 0
        k_iteration = 0
        #print(i)
        for j in testValues1:
            if j == str(_dataFrame.iat[i,1]):
                for k in testValues2:
                    if k == str(_dataFrame.iat[i,2]):
                        #print(str(j_iteration), str(k_iteration))
                        if _dataFrame.iat[i,4] > 0:
                            quantity[j_iteration, k_iteration] += int(_dataFrame.iat[i,0]) * _dataFrame.iat[i,3] * _dataFrame.iat[i,4]
                            #print(quantity[j_iteration, k_iteration])
                        else:
                            quantity[j_iteration, k_iteration] += int(_dataFrame.iat[i,0]) * _dataFrame.iat[i,3]
                            #print(quantity[j_iteration, k_iteration])
                        found[j_iteration,k_iteration] = 1
                    k_iteration += 1
            j_iteration += 1

    print(found)
    #print(quantity)
    df = pd.DataFrame(columns=['Material', 'Presentacion', 'Total'])
    row, col = found.shape
    for i in range(row):
        for j in range(col):
            if found[i,j] != 0:
                i_data = testValues1[i]
                j_data = testValues2[j]
                toApend = pd.Series([i_data, j_data, quantity[i,j]], index=['Material', 'Presentacion', 'Total'])
                print(toApend)

                #df.concat(other=[i_data, j_data], ignore_index=True)
                #pd.concat(df, i_data, j_data)
                df = pd.concat([df, toApend.to_frame().T], ignore_index=True)
    return df

# [C] Constants

# [PF] Program Flow

In [53]:
# File Path Configuration and File Read
xlsxPath = 'AA02A001.xlsx'
xlsxName = xlsxPath.replace('.xlsx', '_M.xlsx')

xlsxSrcDF = pd.read_excel(xlsxPath)

# Clean Type and Hierarchy Columns
xlsxCleanDF = f_cleanTypeAndHierachy(xlsxSrcDF, 0, 'C', 1, '')
xlsxToPrint = f_quantityUpdate(xlsxCleanDF, 1, 4)

# Delete Hierarchy Column
xlsxToPrint = xlsxToPrint.drop(xlsxToPrint.columns[1], axis=1)

# Split DataFrame in Manufacture anď Comercial BOMs and Clean of Blank Spaces
xlsxManufacture = f_splitDataFrame(xlsxToPrint, 0, 'F')
xlsxManufacture = f_cleanBlankSpaces(xlsxManufacture, 1)
xlsxManufactureUnique = f_uniqueQuantity(xlsxManufacture)

xlsxComercial = f_splitDataFrame(xlsxToPrint, 0, 'C')
xlsxComercial = f_cleanBlankSpaces(xlsxComercial, 1)
xlsxComericalUnique = f_uniqueQuantity(xlsxComercial)

['AA02P031' 'AA02S021' 'AA02P035' 'AA02P036' 'AA02P038' 'AA02S013'
 'AA02S002' 'AA02P003' 'AA02P002' 'AA02S001' 'AA02P001' 'AA02S003'
 'AA02P004' 'AA02S012' 'AA02S004' 'AA02P005' 'AA02P006' 'AA02P007'
 'AA02S005' 'AA02P008' 'AA02S006' 'AA02P009' 'AA02P010' 'AA02S007'
 'AA02P011' 'AA02S008' 'AA02P012' 'AA02P013' 'AA02P014' 'AA02S009'
 'AA02P015' 'AA02P016' 'AA02P017' 'AA02S010' 'AA02P018' 'AA02S011'
 'AA02P019' 'AA02S016' 'AA02P022' 'AA02P024' 'AA02P023' 'AA02P025'
 'AA02P026' 'AA02P027' 'AA02S015' 'AA02S014' 'AA02P020' 'AA02P021'
 'AA02S019' 'AA02P030' 'AA02S018' 'AA02S017' 'AA02P028' 'AA02P029'
 'AA02S020' 'AA02P032' 'AA02P033' 'AA02S022' 'AA02P039' 'AA02P040']
0
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
1
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# [TPF] Test Program Flow


In [54]:
rawMaterial = f_rawMaterial(xlsxSrcDF, [4,5,6,7,8,9], 1, 2, 3)
rawMaterial = f_clearNaN(rawMaterial,2)
rawMaterial

Cant.         Material                      Presentación     Largo  \
61       2   ASTM A36 Acero            Cuadrado 0.25" x 0.25"     31.75   
63       3   ASTM A36 Acero            Cuadrado 0.25" x 0.25"     76.20   
64       1   ASTM A36 Acero            Cuadrado 0.25" x 0.25"    138.68   
62       1   AISI 430 A. I.                      Lám. Cal. 10    318.48   
23       1   AISI 430 A. I.                      Lám. Cal. 10    247.61   
18       4   AISI 430 A. I.                      Lám. Cal. 10     76.20   
40       1   AISI 430 A. I.                      Lám. Cal. 10    247.61   
65       2   AISI 430 A. I.                      Lám. Cal. 10     31.75   
43       6   AISI 430 A. I.                      Lám. Cal. 12    101.60   
35       1   AISI 430 A. I.                      Lám. Cal. 12   1371.60   
30       1   AISI 430 A. I.                      Lám. Cal. 12   2159.00   
38       1   AISI 430 A. I.                      Lám. Cal. 12   1371.60   
44       9   AISI 430 A. I.                      Lám. Cal. 12    101.60   
47       2   AISI 430 A. I.                      Lám. Cal. 12    101.60   
52       1   AISI 430 A. I.                      Lám. Cal. 12    101.60   
37       1   AISI 430 A. I.                      Lám. Cal. 12   2159.00   
31       1   AISI 430 A. I.                      Lám. Cal. 12    914.40   
26       1   AISI 430 A. I.                      Lám. Cal. 12   2616.20   
48       2   AISI 430 A. I.                      Lám. Cal. 12    101.60   
22       1   AISI 430 A. I.                      Lám. Cal. 12   2159.00   
15       4   AISI 430 A. I.                      Lám. Cal. 12     50.80   
34       1   AISI 430 A. I.                      Lám. Cal. 12   2159.00   
51       2   AISI 430 A. I.                      Lám. Cal. 12    101.60   
13       4   AISI 430 A. I.                      Lám. Cal. 12    153.82   
3        2   AISI 430 A. I.                      Lám. Cal. 14    513.79   
109      2   AISI 430 A. I.                      Lám. Cal. 14    491.09   
110      2   AISI 430 A. I.                      Lám. Cal. 14    432.59   
2        2   AISI 430 A. I.                      Lám. Cal. 14    491.09   
46       1   AISI 430 A. I.  PTR Cuadrado 1.5" x 1.5" Cal. 14   1135.00   
42       3   AISI 430 A. I.  PTR Cuadrado 1.5" x 1.5" Cal. 14   1516.00   
50       1   AISI 430 A. I.  PTR Cuadrado 1.5" x 1.5" Cal. 14    754.00   
12       1   AISI 430 A. I.      PTR Cuadrado 2" x 2" Cal. 14  20430.20   
29       2   AISI 430 A. I.                  Placa Esp. 3/16"     80.39   
27       2   AISI 430 A. I.                  Placa Esp. 3/16"     80.39   
39       1   AISI 430 A. I.                  Placa Esp. 3/16"     80.39   
90       2   AISI 430 A. I.                  Placa Esp. 3/16"    133.35   
91       2   AISI 430 A. I.                  Placa Esp. 3/16"     31.75   
24       1   AISI 430 A. I.                  Placa Esp. 3/16"     80.39   
33       2   AISI 430 A. I.                  Placa Esp. 3/16"     80.39   
0        1   AISI 430 A. I.                  Redondo de 0.75"      8.00   
60       1  AISI 1018 Acero                     Redondo de 1"   1799.00   
81       4  AISI 1018 Acero                     Redondo de 1"    494.00   
69       8   ASTM A36 Acero                   Redondo de 2.5"     31.75   
85       8  AISI 1018 Acero                   Redondo de 2.5"     31.75   
96       3            A. C.                               N/A    377.83   
86       4              PVC                               N/A   1453.41   
70       4              PVC                               N/A   1453.41   

      Ancho   Peso  
61      NaN   0.01  
63      NaN   0.02  
64      NaN   0.04  
62   158.00   0.63  
23    82.54   0.42  
18    76.20   0.12  
40    82.54   0.42  
65    31.75   0.02  
43    38.10   0.07  
35   169.69   4.56  
30   169.69   7.25  
38   238.28   6.61  
44    53.98   0.08  
47    38.10   0.07  
52    53.98   0.08  
37   238.28  10.39  
31   169.69   3.02  
26   169.69   8.72  
48   

In [55]:
values = rawMaterial.iloc[:,1]
values = values.unique()
values

array(['ASTM A36 Acero', 'AISI 430 A. I.', 'AISI 1018 Acero', 'A. C.',
       'PVC'], dtype=object)

In [56]:
values2 = rawMaterial.iloc[:,2]
values2 = values2.unique()
values2

array(['Cuadrado 0.25" x 0.25"', 'Lám. Cal. 10', 'Lám. Cal. 12',
       'Lám. Cal. 14', 'PTR Cuadrado 1.5" x 1.5" Cal. 14',
       'PTR Cuadrado 2" x 2" Cal. 14', 'Placa Esp. 3/16"',
       'Redondo de 0.75"', 'Redondo de 1"', 'Redondo de 2.5"', 'N/A'],
      dtype=object)

In [57]:
xlsxRawMaterialUnique = f_uniqueRawQuantity(rawMaterial)
xlsxRawMaterialUnique

['ASTM A36 Acero' 'AISI 430 A. I.' 'AISI 1018 Acero' 'A. C.' 'PVC']
['Cuadrado 0.25" x 0.25"' 'Lám. Cal. 10' 'Lám. Cal. 12' 'Lám. Cal. 14'
 'PTR Cuadrado 1.5" x 1.5" Cal. 14' 'PTR Cuadrado 2" x 2" Cal. 14'
 'Placa Esp. 3/16"' 'Redondo de 0.75"' 'Redondo de 1"' 'Redondo de 2.5"'
 'N/A']
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Material                ASTM A36 Acero
Presentacion    Cuadrado 0.25" x 0.25"
Total                           430.78
dtype: object
Material         ASTM A36 Acero
Presentacion    Redondo de 2.5"
Total                     254.0
dtype: object
Material        AISI 430 A. I.
Presentacion      Lám. Cal. 10
Total              116437.1838
dtype: object
Material        AISI 430 A. I.
Presentacion      Lám. Cal. 12
Total              3113278.762
dtype: object
Material        AISI 430 A. I.
Presentacion      Lám. Cal. 14
Total          

Material                      Presentacion        Total
0    ASTM A36 Acero            Cuadrado 0.25" x 0.25"       430.78
1    ASTM A36 Acero                   Redondo de 2.5"        254.0
2    AISI 430 A. I.                      Lám. Cal. 10  116437.1838
3    AISI 430 A. I.                      Lám. Cal. 12  3113278.762
4    AISI 430 A. I.                      Lám. Cal. 14   812159.722
5    AISI 430 A. I.  PTR Cuadrado 1.5" x 1.5" Cal. 14       6437.0
6    AISI 430 A. I.      PTR Cuadrado 2" x 2" Cal. 14      20430.2
7    AISI 430 A. I.                  Placa Esp. 3/16"   28460.9946
8    AISI 430 A. I.                  Redondo de 0.75"          8.0
9   AISI 1018 Acero                     Redondo de 1"       3775.0
10  AISI 1018 Acero                   Redondo de 2.5"        254.0
11            A. C.                               N/A      1133.49
12              PVC                               N/A  770423.5728

In [58]:
writer = ExcelWriter(xlsxName)

xlsxSrcDF = xlsxSrcDF.reset_index(drop=True)
xlsxSrcDF.to_excel(writer,'Source')

xlsxManufactureUnique = xlsxManufactureUnique.reset_index(drop=True)
xlsxManufactureUnique.to_excel(writer,'Manufacture')

xlsxComericalUnique = xlsxComericalUnique.reset_index(drop=True)
xlsxComericalUnique.to_excel(writer, 'Comercial')

xlsxRawMaterialUnique.to_excel(writer, 'RawMaterials')


writer.save()
writer.close()

C:\Users\erodr\AppData\Local\Temp\ipykernel_21052\3829285009.py:15: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()


In [59]:
doc = Document()
page = Page(PageSize.TABLOID_LANDSCAPE.value[0], PageSize.TABLOID_LANDSCAPE.value[1],)

doc.add_page(page)
pageLayOut = SingleColumnLayoutWithOverflow(page)
pageLayOut._vertical_margin_top = page.get_page_info().get_height() * Decimal(0.02)
pageLayOut._vertical_margin_bottom = page.get_page_info().get_height() * Decimal(0.02)
pageLayOut._horizontal_margin = page.get_page_info().get_width() * Decimal(0.01)

rows, columns = xlsxManufacture.shape
xlsxManufactureArray = xlsxManufacture.to_numpy()


In [60]:

xlsxManufactureArray.

SyntaxError: invalid syntax (1746554950.py, line 1)

In [ ]:
from borb.pdf.canvas.color.color import HexColor, X11Color
from borb.pdf.canvas.layout.table.fixed_column_width_table import FixedColumnWidthTable as Table
#from borb.pdf.canvas.layout.table.flexible_column_width_table import FlexibleColumnWidthTable as Table
rows, columns = xlsxManufacture.shape
columnsDF = xlsxManufacture.columns.to_numpy()

manufactureTable = Table(number_of_rows = rows, number_of_columns = columns)
for h in  columnsDF:
    manufactureTable.add(
        TableCell(
            Paragraph(h, font_color=X11Color("White")),
            background_color=HexColor("016934")
        )
    )
print(xlsxManufactureArray.shape)
data = 0
for i in iter(xlsxManufactureArray):
    print(i)
    for j in range(len(i):
        print(j)
        print(i[j])
        data = i[j]
        print(data)
        manufactureTable.add(Paragraph(data))





pageLayOut.add(manufactureTable)

with open("output.pdf", "wb") as out_file_handle:
    PDF.dumps(out_file_handle, doc)

In [ ]:
x
pageLayOut.add(
    #TableUtil.from_2d_array(xlsxManufactureArray,flexible_column_width=True)
    #TableCell.

    )
# store
with open("output.pdf", "wb") as out_file_handle:
    PDF.dumps(out_file_handle, doc)

In [ ]:
xlsxRawMaterial = xlsxSrcDF[xlsxSrcDF.columns[[4,5,6,7,8]]]
srie = xlsxRawMaterial.columns.values.tolist()
print(srie)

xlsxRawMaterial = xlsxRawMaterial.sort_values(by=srie[1])
xlsxRawMaterial = xlsxRawMaterial.sort_values(by=srie[2])

xlsxRawMaterial = xlsxRawMaterial[xlsxRawMaterial[srie[3]] > 0]
xlsxRawMaterial

In [ ]:
                if found[i_iteration] == 0:
                    found[i_iteration] = 1
                    quantity[i_iteration] += int(_dataFrame.iat[i,3])
                else:
                    quantity[i_iteration] += int(_dataFrame.iat[i,3])
                    rowToDelete[i] = _dataFrame.index.values[i]
                found[i_iteration] = 1
                print(found)
            i_iteration += 1

    for i in rowToDelete:
        if i != 0:
            uniqueDataFrame = uniqueDataFrame.drop(i)
            #print(j)

    print('Result')
    print(found)
    print(quantity)
    print(rowToDelete)

    i_iteration = 0
    for i in quantity:
        print(i)
        print(i_iteration)
        uniqueDataFrame.iat[i_iteration,3] = i
        i_iteration += 1